# Generated by Django 4.2.3 on 2023-08-01 09:20

import app1.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, validators=[app1.models.validate_name])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[app1.models.validate_name])),
                ('last_name', models.CharField(max_length=50, validators=[app1.models.validate_name])),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('login_created_at', models.DateTimeField(auto_now_add=True)),
                ('login_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('login_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.role')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50, validators=[app1.models.validate_name])),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
